### ISSUE TITLE
"Delete" key no longer removes events.

### ISSUE THREAD

**Issue by miguelgaspar24** [UmSenhorQualquer/pythonVideoAnnotator#44]
The "Delete" key doesn't remove events from any given track anymore. The only option now is to select the event of interest, right-click on it, and then select "Remove event", which is much more time consuming.

The "Delete" functionality used to work in previous versions.

This behavior has been observed independently in two different laptops with the following properties:
 - Windows 8.1 + Python Video Annotator version 3.108
 - Windows 10 Pro + Python Video Annotator version 3.306

**Comment by MicBoucinha** [comment]
The shortcuts were updated in the last version. I believe that they were changed due to a new feature. 

You can check them here: https://pythonvideoannotator.readthedocs.io/en/master/user-docs/shortcuts/index.html

**Comment by miguelgaspar24** [comment]
Indeed! The new shortcut does work. Sorry for the oversight.
Thanks!
